### ISSUE TITLE
startFrom and maxItems should be treated as a String

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns-js#34]
As of https://github.com/vinyldns/vinyldns/pull/583 zone paging will treat startFrom and nextId as a string. If possible when reading any startFrom and nextId from json it would be useful to read it and send it back as a String, as the API will parse the query parameter as an Int if needed

**Comment by mdb** [comment]
@nimaeskandary Thanks for creating this! Can you elaborate a bit on the requirements and action items for `vinyldns-js`, specifically? Links to relevant `vinyldns-js` source code may be helpful too.

I ask because, in current implementation, I _believe_ `vinyldns-js` only makes use of these fields when adding URL query params in calling the VinylDNS API and will therefore work as expected in each of the following scenarios:

```javascript
// strings
vinyldns.getRecordSets({
  nextId: '1',
  maxItems: '2'
})
```
```javascript
// integers
vinyldns.getRecordSets({
  nextId: 1,
  maxItems: 2
})
```

**Comment by nimaeskandary** [comment]
I see you're right that when the request is made it doesn't matter since they will be query strings. I guess it is just important to validate that when you are reading the nextId from a response you don't try to read it as an Int since it will come back as string, but if nothing is strongly typed then it wouldn't matter
